import logging
from typing import TypeVar

import pyrogram
from pyrogram import raw
from pyrogram.raw.core import TLObject
from pyrogram.session import Session

log = logging.getLogger(__name__)

ReturnType = TypeVar('ReturnType')


class Invoke:
    async def invoke(
        self: "pyrogram.Client",
        query: TLObject[ReturnType],
        retries: int = Session.MAX_RETRIES,
        timeout: float = Session.WAIT_TIMEOUT,
        sleep_threshold: float = None,
        retry_delay: float = Session.RETRY_DELAY,
        recaptcha_token: str = None,
        business_connection_id: str = None
    ) -> ReturnType:
        """Invoke raw Telegram functions.

        This method makes it possible to manually call every single Telegram API method in a low-level manner.
        Available functions are listed in the :obj:`functions <pyrogram.api.functions>` package and may accept compound
        data types from :obj:`types <pyrogram.api.types>` as well as bare types such as ``int``, ``str``, etc...

        .. note::

            This is a utility method intended to be used **only** when working with raw
            :obj:`functions <pyrogram.api.functions>` (i.e: a Telegram API method you wish to use which is not
            available yet in the Client class as an easy-to-use method).

        .. include:: /_includes/usable-by/users-bots.rst

        Parameters:
            query (``RawFunction``):
                The API Schema function filled with proper arguments.

            retries (``int``, *optional*):
                Number of retries.

            timeout (``float``, *optional*):
                Timeout in seconds.

            sleep_threshold (``float``, *optional*):
                Sleep threshold in seconds.

            retry_delay (``float``, *optional*):
                Retry delay in seconds on errors.

            recaptcha_token (``str``, *optional*):
                ReCaptcha token.

            business_connection_id (``str``, *optional*):
                Unique identifier of the business connection.

        Returns:
            ``RawType``: The raw type response generated by the query.

        Raises:
            RPCError: In case of a Telegram RPC error.
        """
        if not self.is_connected:
            raise ConnectionError("Client has not been started yet")

        session = self.session

        if business_connection_id:
            query = raw.functions.InvokeWithBusinessConnection(
                connection_id=business_connection_id,
                query=query
            )

            session = await self.get_session(business_connection_id=business_connection_id)

        if recaptcha_token:
            query = raw.functions.InvokeWithReCaptcha(token=recaptcha_token, query=query)

        if self.no_updates:
            query = raw.functions.InvokeWithoutUpdates(query=query)

        if self.takeout_id:
            query = raw.functions.InvokeWithTakeout(takeout_id=self.takeout_id, query=query)

        r = await session.invoke(
            query=query, retries=retries, timeout=timeout,
            sleep_threshold=(
                sleep_threshold if sleep_threshold is not None else self.sleep_threshold
            ),
            retry_delay=retry_delay
        )

        await self.fetch_peers(getattr(r, "users", []))
        await self.fetch_peers(getattr(r, "chats", []))

        return r